backends/baguette-buddy-ror/config/routes.rb
Rails.application.routes.draw do
  root 'home#welcome'

  scope constraints: {format: :html} do
    get 'sign_up', to: 'users#new', as: :sign_up
    post 'sign_up', to: 'users#create'
  
    get "login", to: "sessions#new", as: :login
    post "login", to: "sessions#create"
    delete "logout", to: "sessions#destroy", as: :logout
    resources :receipes
  end


  namespace :api, constraints: {format: :json} do
    resources :receipes
    resources :ingredients
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

backends/baguette-buddy-ror/app/models/receipe.rb
class Receipe < ApplicationRecord
  before_validation :generate_slug
  belongs_to :user
  has_many :ingredients

  validates :title, presence: true, uniqueness: true
  validates :slug, presence: true, uniqueness: true
  validates :description, presence: true
  validates :portions_number, numericality: {greater_than_or_equal_to: 1}
  validates :cooking_time, numericality: {greater_than_or_equal_to: 1}

  def base64_content
    Base64.encode64(self.illustration.to_s)
  end

  def image_type
    image_content_type(self.base64_content)
  end

  def base64_data
    data = "data:#{self.image_type};base64, #{self.base64_content}"
    return data
  end

  private

  def generate_slug
    self.slug = self.title.parameterize.underscore if self.title
  end

  IMAGE_SIGNATURES = {
    R0lGODdh: 'image/gif',
    R0lGODlh: 'image/gif',
    iVBORw0KGgo: 'image/png',
    '/9j/': 'image/jpg',
    Qk02U: 'image/bmp',
    '/9sIA+gD': 'image/jpeg',
    '/0x90h+': 'image/tiff',
    RAwwAHQAu: 'image/webp',
    UklGR: 'image/webp',
  }

  def image_content_type(content)
    return IMAGE_SIGNATURES.find do |signature, content_type|
      return content_type if content.start_with?(signature.to_s)
    end
  end
end

backends/baguette-buddy-ror/app/controllers/api/receipes_controller.rb
class Api::ReceipesController < ApplicationController
  before_action :set_receipe, only: %i[ show update destroy ]
  skip_before_action :verify_authenticity_token

  # GET /api/recipes
  def index
    @receipes = Receipe.all
  end

  # GET /api/recipes/1
  def show
  end

  # POST /api/recipes
  def create
    @receipe = Receipe.new(receipe_params)
    if receipe_params[:illustration]
      @receipe.illustration = optimize_illustration(receipe_params[:illustration].path)
    end

    if @receipe.save
      render :show, status: :created, location: @receipe
    else
      render json: @receipe.errors, status: :unprocessable_entity
    end
  end
  
  # PUT/PATCH /api/recipes/:id
  def update
    if receipe_params[:illustration]
      @receipe.illustration = optimize_illustration(receipe_params[:illustration].path)
    end

    if @receipe.update(receipe_params.reject{|k, _| k.in?([:illustration, "illustration"])})
      render :show, status: :ok, location: @receipe
    else
      render json: @receipe.errors, status: :unprocessable_entity
    end
  end
  
  # DELETE /api/recipes/:id
  def destroy
    @receipe.destroy!

    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private

  def set_receipe
    @receipe = Receipe.find(params[:id])
  end

  def receipe_params
    params.require(:receipe).permit(:title, :description, :user_id, :portions_number, :illustration)
  end
end

backends/baguette-buddy-ror/app/controllers/receipes_controller.rb
class ReceipesController < ApplicationController
  before_action :set_receipe, only: %i[ show edit update destroy ]

  # GET /receipes
  def index
    @receipes = Receipe.all
  end

  # GET /receipes/1
  def show
  end

  # GET /receipes/new
  def new
    @receipe = Receipe.new
    @users = User.all.collect{|u| [u.username, u.id]}
  end

  # GET /receipes/1/edit
  def edit
  end

  # POST /receipes
  def create
    @receipe = Receipe.new(receipe_params)
    if receipe_params[:illustration]
      @receipe.illustration = optimize_illustration(receipe_params[:illustration].path)
    end

    if @receipe.save
      redirect_to @receipe, notice: "Receipe was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /receipes/1
  def update
    if receipe_params[:illustration]
      @receipe.illustration = optimize_illustration(receipe_params[:illustration].path)
    end

    if @receipe.update(receipe_params.reject{|k, _| k.in?([:illustration, 'illustration'])})
      redirect_to @receipe, notice: "Receipe was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /receipes/1
  def destroy
    @receipe.destroy!

    respond_to do |format|
      format.html { redirect_to receipes_path, status: :see_other, notice: "Receipe was successfully destroyed." }
    end
  end

  private

  # Allow fetching receipe either by id or slug
  def set_receipe
    identifier = params[:id]
    if identifier.to_s.match /^\h{8}-(\h{4}-){3}\h{12}$/
      @receipe = Receipe.find(identifier)
    else
      @receipe = Receipe.find_by(slug: identifier)
    end
  end

  def receipe_params
    params.require(:receipe).permit(:title, :description, :user_id, :portions_number, :illustration)
  end
end

backends/baguette-buddy-ror/app/helpers/api/receipes_helper.rb
module Api::ReceipesHelper
end

backends/baguette-buddy-ror/app/helpers/receipes_helper.rb
require 'redcarpet'

module ReceipesHelper
  
  def description_as_html(description)
    options = {
        filter_html:     true,
        hard_wrap:       true,
        link_attributes: { rel: 'nofollow', target: "_blank" , class: "underline"},
        space_after_headers: true,
        fenced_code_blocks: true,
        safe_links_only: true,
        tables: true,
    }
    extensions = {
        autolink:           true,
        superscript:        true,
        disable_indented_code_blocks: true,
        strikethrough: true,
        space_after_headers: true,
        tables: true,
        quote: true,
        hard_wrap:       true,
    }
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML.new(options), extensions)
    return if description.nil? || description.empty?
    markdown.render(description).html_safe
  end
end

backends/baguette-buddy-ror/app/views/receipes/_form.html.erb
<%= form_with(model: receipe, class: 'max-w-md mx-auto') do |form| %>
  <% if receipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(receipe.errors.count, "error") %> prohibited this receipe from being saved:</h2>

      <ul>
        <% receipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='relative z-0 w-full mb-5 group'>
    <%= form.text_field :title, required: true, class: 'block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer' %>
    <%= form.label :title, class: 'peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6' %>
  </div>

  <div class='relative z-0 w-full mb-5 group'>
    <%= form.text_area :description, required: true, rows: (receipe.description ? receipe.description.length / 60 : 10), class: 'block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer' %>
    <%= form.label :description, class: 'peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6' %>
  </div>

  <% if @current_user %>
    <%= form.hidden_field :user_id, value: @current_user.id %>
  <% end %>

  <div class='relative z-0 w-full mb-5 group'>
    <%= form.number_field :portions_number, required: true, minimum: 1, class: 'block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer' %>
    <%= form.label :portions_number, class: 'peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6' %>
  </div>

  <%= form.label :illustration, class: 'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
  <%= form.file_field :illustration, accept: 'image/*', class: 'block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400', 'aria-describedby': 'user_avatar_help' %>
  <div class="mt-1 text-sm text-gray-500 dark:text-gray-300" id="user_avatar_help">A profile picture is useful to confirm your are logged into your account</div>

  <div class='relative z-0 w-full my-5 group'>
    <%= form.submit "Save", class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
  </div>
<% end %>

backends/baguette-buddy-ror/app/views/receipes/_receipe.html.erb
<div class="grid grid-cols-1 md:grid-cols-5 gap-4 receipe-show">
    <div class="col-span-2">
      <%= image_tag("data:#{receipe.image_type};base64, #{Base64.encode64(receipe.illustration.to_s)}", alt: 'illustration', class: 'object-cover w-full') %>
    </div>
    <div class="col-span-3">
      <div class="data w-full max-w-xl">
        <h2 class="font-manrope font-bold text-3xl leading-10 text-gray-900 mb-2 capitalize">
          <%= @receipe.title %>
        </h2>
        <div>
          <p class="mb-2">Below should ingredients be listed</p>
          <ul class="grid gap-y-4 mb-8">
            <li class="flex items-center gap-3">
                <svg width="26" height="26" viewBox="0 0 26 26" fill="none"
                    xmlns="http://www.w3.org/2000/svg">
                    <rect width="26" height="26" rx="13" fill="#4F46E5" />
                    <path
                        d="M7.66669 12.629L10.4289 15.3913C10.8734 15.8357 11.0956 16.0579 11.3718 16.0579C11.6479 16.0579 11.8701 15.8357 12.3146 15.3913L18.334 9.37183"
                        stroke="white" stroke-width="1.6" stroke-linecap="round" />
                </svg>
                <span class="font-normal text-base text-gray-900 ">Branded shirt</span>
            </li>
            <li class="flex items-center gap-3">
                <svg width="26" height="26" viewBox="0 0 26 26" fill="none"
                    xmlns="http://www.w3.org/2000/svg">
                    <rect width="26" height="26" rx="13" fill="#4F46E5" />
                    <path
                        d="M7.66669 12.629L10.4289 15.3913C10.8734 15.8357 11.0956 16.0579 11.3718 16.0579C11.6479 16.0579 11.8701 15.8357 12.3146 15.3913L18.334 9.37183"
                        stroke="white" stroke-width="1.6" stroke-linecap="round" />
                </svg>
                <span class="font-normal text-base text-gray-900 ">3 color shirt</span>
            </li>
            <li class="flex items-center gap-3">
                <svg width="26" height="26" viewBox="0 0 26 26" fill="none"
                    xmlns="http://www.w3.org/2000/svg">
                    <rect width="26" height="26" rx="13" fill="#4F46E5" />
                    <path
                        d="M7.66669 12.629L10.4289 15.3913C10.8734 15.8357 11.0956 16.0579 11.3718 16.0579C11.6479 16.0579 11.8701 15.8357 12.3146 15.3913L18.334 9.37183"
                        stroke="white" stroke-width="1.6" stroke-linecap="round" />
                </svg>
                <span class="font-normal text-base text-gray-900 ">Pure Cotton Shirt with 60% as
                    40%</span>
            </li>
            <li class="flex items-center gap-3">
                <svg width="26" height="26" viewBox="0 0 26 26" fill="none"
                    xmlns="http://www.w3.org/2000/svg">
                    <rect width="26" height="26" rx="13" fill="#4F46E5" />
                    <path
                        d="M7.66669 12.629L10.4289 15.3913C10.8734 15.8357 11.0956 16.0579 11.3718 16.0579C11.6479 16.0579 11.8701 15.8357 12.3146 15.3913L18.334 9.37183"
                        stroke="white" stroke-width="1.6" stroke-linecap="round" />
                </svg>
                <span class="font-normal text-base text-gray-900 ">all size is available</span>
            </li>
          </ul>
        </div>
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-3 py-8">
          <div class="flex sm:items-center sm:justify-center w-full">
              <button
                  class="group py-4 px-6 border border-gray-400 rounded-l-full bg-white transition-all duration-300 hover:bg-gray-50 hover:shadow-sm hover:shadow-gray-300">
                  <svg class="stroke-gray-900 group-hover:stroke-black" width="22" height="22"
                      viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path d="M16.5 11H5.5" stroke="" stroke-width="1.6" stroke-linecap="round" />
                      <path d="M16.5 11H5.5" stroke="" stroke-opacity="0.2" stroke-width="1.6"
                          stroke-linecap="round" />
                      <path d="M16.5 11H5.5" stroke="" stroke-opacity="0.2" stroke-width="1.6"
                          stroke-linecap="round" />
                  </svg>
              </button>
              <input type="text"
                  class="font-semibold text-gray-900 cursor-pointer text-lg py-[13px] px-6 w-full sm:max-w-[118px] outline-0 border-y border-gray-400 bg-transparent placeholder:text-gray-900 text-center hover:bg-gray-50"
                  placeholder="<%= @receipe.portions_number %>">
              <button
                  class="group py-4 px-6 border border-gray-400 rounded-r-full bg-white transition-all duration-300 hover:bg-gray-50 hover:shadow-sm hover:shadow-gray-300">
                <svg class="stroke-gray-900 group-hover:stroke-black" width="22" height="22"
                    viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M11 5.5V16.5M16.5 11H5.5" stroke="#9CA3AF" stroke-width="1.6"
                        stroke-linecap="round" />
                    <path d="M11 5.5V16.5M16.5 11H5.5" stroke="black" stroke-opacity="0.2"
                        stroke-width="1.6" stroke-linecap="round" />
                    <path d="M11 5.5V16.5M16.5 11H5.5" stroke="black" stroke-opacity="0.2"
                        stroke-width="1.6" stroke-linecap="round" />
                </svg>
            </button>
          </div>
          <button class="group py-4 px-5 rounded-full bg-indigo-50 text-indigo-600 font-semibold text-lg w-full flex items-center justify-center gap-2 transition-all duration-500 hover:bg-indigo-100">
            <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" viewBox="0 0 26 26"
                  fill="none">
                  <path
                      d="M4.47084 14.3196L13.0281 22.7501L21.9599 13.9506M13.0034 5.07888C15.4786 2.64037 19.5008 2.64037 21.976 5.07888C24.4511 7.5254 24.4511 11.4799 21.9841 13.9265M12.9956 5.07888C10.5204 2.64037 6.49824 2.64037 4.02307 5.07888C1.54789 7.51738 1.54789 11.4799 4.02307 13.9184M4.02307 13.9184L4.04407 13.939M4.02307 13.9184L4.46274 14.3115"
                      stroke="#4F46E5" stroke-width="1.6" stroke-miterlimit="10"
                      stroke-linecap="round" stroke-linejoin="round" />
              </svg>

            Add to favorites
          </button>
        </div>
      </div>
    </div>
    <div class="col-span-3 col-start-2">
      <p class="text-gray-500 text-base font-normal my-5 description">
        <%= description_as_html(@receipe.description) %>
        <a href="#" class="text-indigo-600">More....</a>
      </p>
    </div>
  </div>
</div>

backends/baguette-buddy-ror/app/views/receipes/_receipe_card.html.erb
<div id="<%= dom_id receipe %>" class="receipe-card">
  <%= image_tag(receipe.base64_data, alt: 'illustration', class: 'rounded-t-lg h-48 w-full object-cover') %>
  <div class="p-5">
    <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
      <%= receipe.title %>
    </h5>

    <span class="mb-3 font-normal text-sm text-gray-700 dark:text-gray-400">
      @<%= receipe.user.username %>
    </span>

    <p class="my-3 font-normal text-gray-200 dark:text-gray-200">
      <%= description_as_html(receipe.description.truncate(100, separator: ' ', ommission: '...')) %>
    </p>

    <p class="text-xs">
      <strong>Portions number:</strong>
      <%= receipe.portions_number %>
    </p>
  </div>
</div>

backends/baguette-buddy-ror/app/views/receipes/edit.html.erb
<h1>Editing receipe</h1>

<%= render "form", receipe: @receipe %>

<br>

<div class="inline-flex rounded-md shadow-xs gap-0">
  <%= link_to(receipes_path, class: 'inline-flex items-center px-4 py-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-s-lg hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:text-white dark:hover:bg-gray-700 dark:focus:ring-blue-500 dark:focus:text-white')  do %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-3 h-3 me-2">
      <path stroke-linecap="round" stroke-linejoin="round" d="M9 15 3 9m0 0 6-6M3 9h12a6 6 0 0 1 0 12h-3" />
    </svg>
    Back to receipes

  <% end %>
  <%= link_to(@receipe, class: 'inline-flex items-center px-4 py-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-e-lg hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:text-white dark:hover:bg-gray-700 dark:focus:ring-blue-500 dark:focus:text-white')  do %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-3 h-3 me-2">
      <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 0 1 0-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178Z" />
      <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
    </svg>
    Show this receipe
  <% end %>
</div>

backends/baguette-buddy-ror/app/views/receipes/index.html.erb
<div class="h-screen">
  <div>
  <p style="color: green"><%= notice %></p>

  <div class="lg:flex lg:items-center lg:justify-between pr-16 mb-6">
    <div class="min-w-0 flex-1">
      <h2 class="text-2xl/7 font-bold text-gray-900 sm:truncate sm:text-3xl sm:tracking-tight">Receipes</h2>
    </div>
    <div class="mt-5 flex lg:mt-0 lg:ml-4">
      <span class="sm:ml-3 cursor-pointer">
        <%= link_to(new_receipe_path, class: 'button inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-xs hover:bg-indigo-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 cursor-pointer') do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="mr-1.5 -ml-0.5 size-5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
          </svg>
          New Receipe
        <% end %>
      </span>
      <span class="sm:ml-3 cursor-pointer">
        <%= button_to(logout_path, method: :delete, class: 'button inline-flex items-center rounded-md bg-red-600 px-3 py-2 text-sm font-semibold text-white shadow-xs hover:bg-red-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-600 cursor-pointer') do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="mr-1.5 -ml-0.5 size-5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 9V5.25A2.25 2.25 0 0 1 10.5 3h6a2.25 2.25 0 0 1 2.25 2.25v13.5A2.25 2.25 0 0 1 16.5 21h-6a2.25 2.25 0 0 1-2.25-2.25V15m-3 0-3-3m0 0 3-3m-3 3H15" />
          </svg>
          Log out
        <% end %>
      </span>
    </div>
  </div>
  </div>
  <div id="receipes" class="grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-4">
    <% @receipes.each do |receipe| %>
      <%= link_to(receipe_path(receipe.slug), class: 'max-w-sm bg-white border border-gray-200 rounded-lg shadow-sm dark:bg-gray-800 dark:border-gray-700 bg-gray hover:border hover:border-white hover:scale-102 duration-700') do %>
        <%= render "receipes/receipe_card", receipe: receipe %>
      <% end %>
    <% end %>
  </div>

</div>

backends/baguette-buddy-ror/app/views/receipes/new.html.erb
<div>
  <h1>New receipe</h1>

  <%= render "form", receipe: @receipe %>

  <br>

  <div>
    <%= link_to "Back to receipes", receipes_path %>
  </div>
</div>

backends/baguette-buddy-ror/app/views/receipes/show.html.erb
<div class="">
  <p style="color: green"><%= notice %></p>

  <div class="border-b border-slate-400 w-full my-5 pb-5 print:hidden">
    <div class="inline-flex rounded-md shadow-xs">
      <%= link_to(receipes_path, class: 'inline-flex items-center px-4 py-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-s-lg hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:text-white dark:hover:bg-gray-700 dark:focus:ring-blue-500 dark:focus:text-white')  do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-3 h-3 me-2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M9 15 3 9m0 0 6-6M3 9h12a6 6 0 0 1 0 12h-3" />
        </svg>
        Back to receipes

      <% end %>
      <%= link_to(edit_receipe_path(@receipe), class: 'inline-flex items-center px-4 py-2 text-sm font-medium text-gray-900 bg-white border-t border-b border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:text-white dark:hover:bg-gray-700 dark:focus:ring-blue-500 dark:focus:text-white')  do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-3 h-3 me-2">
          <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L6.832 19.82a4.5 4.5 0 0 1-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 0 1 1.13-1.897L16.863 4.487Zm0 0L19.5 7.125" />
        </svg>

        Edit this receipe
      <% end %>
      <%= button_to @receipe, method: :delete, class: 'inline-flex items-center px-4 py-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-e-lg hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:text-white dark:hover:bg-gray-700 dark:focus:ring-blue-500 dark:focus:text-white' do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-3 h-3 me-2 text-red-400">
          <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
        </svg>
        Destroy this receipe
      <% end %>
    </div>
  </div>

  <%= render @receipe %>
</div>